name: Publish Wiki

on:
  release:
    type: [publish]

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run wiki
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        name: Wiki Push
        with:
          path: "./wiki"
          token: ${{ secrets.GITHUB_TOKEN }}